{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "\n# Parametric Study\n\n`skewExample.py` from [Using a script to perform a parametric study](https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAECMDRefMap/simacmd-c-intexaaclskewparametric.htm?contextscope=all&id=c78341a7f00b493caa61a4c530165d52).\n\nThis script performs a parameter study of element type versus \nskew angle. For more details, see Problem 2.3.4 in the \nAbaqus Benchmarks manual.\n\nRun the following command before running this script:\n\n```sh\nabaqus fetch job=viewer_tutorial\n```\nThe following shows the contents of the script skewExample.py. The parametric study does the following:\n\n- Opens the model database and creates variables that refer to the part, the assembly, and the part instance stored in `Model-1`.\n- Creates variables that refer to the four faces and the nine vertices in the instance of the planar shell part.\n- Skews the plate by modifying the angular dimension in the sketch of the base feature.\n- Defines the logical corners of the four faces, and generates a structured mesh.\n- Runs the analysis for a range of angles using two element types for each angle.\n- Calculates the maximum moment and displacement at the center of the shell.\n- Displays **X - Y** plots in separate viewports of the following:\n\n  - Displacement versus skew angle\n  - Maximum bending moment versus skew angle\n  - Minimum bending moment versus skew angle\n\n  The theoretical results are also plotted.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "collapsed": false
      },
      "outputs": [],
      "source": [
        "import visualization\nfrom abaqus import *\nfrom abaqusConstants import *\n\n\n# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ndef getResults():\n    \"\"\"\n    Retrieve the displacement and calculate the minimum\n    and maximum bending moment at the center of plate.\n    \"\"\"\n\n    from visualization import ELEMENT_NODAL\n\n    # Open the output database.\n\n    odb = visualization.openOdb(\"skew.odb\")\n    centerNSet = odb.rootAssembly.nodeSets[\"CENTER\"]\n    frame = odb.steps[\"Step-1\"].frames[-1]\n\n    # Retrieve Z-displacement at the center of the plate.\n\n    dispField = frame.fieldOutputs[\"U\"]\n    dispSubField = dispField.getSubset(region=centerNSet)\n    disp = dispSubField.values[0].data[2]\n\n    # Average the contribution from each element to the moment,\n    # then calculate the minimum and maximum bending moment at\n    # the center of the plate using Mohr's circle.\n\n    momentField = frame.fieldOutputs[\"SM\"]\n    momentSubField = momentField.getSubset(region=centerNSet, position=ELEMENT_NODAL)\n    m1, m2, m3 = 0, 0, 0\n    for value in momentSubField.values:\n        m1 = m1 + value.data[0]\n        m2 = m2 + value.data[1]\n        m3 = m3 + value.data[2]\n    numElements = len(momentSubField.values)\n    m1 = m1 / numElements\n    m2 = m2 / numElements\n    m3 = m3 / numElements\n    momentA = 0.5 * (abs(m1) + abs(m2))\n    momentB = sqrt(0.25 * (m1 - m2) ** 2 + m3**2)\n    maxMoment = momentA + momentB\n    minMoment = momentA - momentB\n\n    odb.close()\n\n    return disp, maxMoment, minMoment\n\n\n# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ndef createXYPlot(vpOrigin, vpName, plotName, data):\n    \"\"\"\n    Display curves of theoretical and computed results in\n    a new viewport.\n    \"\"\"\n\n    from visualization import USER_DEFINED\n\n    vp = session.Viewport(name=vpName, origin=vpOrigin, width=150, height=100)\n    xyPlot = session.XYPlot(plotName)\n    chart = xyPlot.charts.values()[0]\n    curveList = []\n    for elemName, xyValues in sorted(data.items()):\n        xyData = session.XYData(elemName, xyValues)\n        curve = session.Curve(xyData)\n        curveList.append(curve)\n    chart.setValues(curvesToPlot=curveList)\n    chart.axes1[0].axisData.setValues(useSystemTitle=False, title=\"Skew Angle\")\n    chart.axes2[0].axisData.setValues(useSystemTitle=False, title=plotName)\n    vp.setValues(displayedObject=xyPlot)\n\n\n# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ndef createModel():\n    \"\"\"\n    Create the skew example model, including material, step, load, bc, and job.\n    \"\"\"\n\n    import mesh\n    import part\n    import regionToolset\n    import step\n\n    # Create the Plate\n    m = mdb.models[\"Model-1\"]\n    s = m.ConstrainedSketch(name=\"__profile__\", sheetSize=5.0)\n    g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints\n    s.sketchOptions.setValues(\n        sheetSize=5.0,\n        gridSpacing=0.1,\n        grid=ON,\n        gridFrequency=2,\n        constructionGeometry=ON,\n        dimensionTextHeight=0.1,\n        decimalPlaces=2,\n    )\n    s.setPrimaryObject(option=STANDALONE)\n    s.rectangle(point1=(0.0, 0.0), point2=(1.0, 1.0))\n    s.delete(objectList=(c[21], c[18], c[19], c[20]))\n    s.HorizontalConstraint(entity=g.findAt((0.5, 0.0)))\n    s.FixedConstraint(entity=v.findAt((0.0, 0.0)))\n    s.FixedConstraint(entity=v.findAt((1.0, 0.0)))\n    s.ParallelConstraint(entity1=g.findAt((0.0, 0.5)), entity2=g.findAt((1.0, 0.5)))\n    s.AngularDimension(line1=g.findAt((0.0, 0.5)), line2=g.findAt((0.5, 0.0)), textPoint=(0.2, 0.2), value=90.0)\n    p = m.Part(name=\"Plate\", dimensionality=THREE_D, type=DEFORMABLE_BODY)\n    p.BaseShell(sketch=s)\n    s.unsetPrimaryObject()\n    vp = session.viewports[\"Viewport: 1\"]\n    vp.setValues(displayedObject=p)\n    del mdb.models[\"Model-1\"].sketches[\"__profile__\"]\n\n    # Create the Steel material\n    m.Material(\"Steel\")\n    m.materials[\"Steel\"].Elastic(table=((30.0e6, 0.3),))\n    m.HomogeneousShellSection(\n        name=\"Shell\",\n        preIntegrate=OFF,\n        material=\"Steel\",\n        thickness=0.01,\n        poissonDefinition=DEFAULT,\n        temperature=GRADIENT,\n        integrationRule=SIMPSON,\n        numIntPts=5,\n    )\n\n    # Assign Steel to the plate\n    p = mdb.models[\"Model-1\"].parts[\"Plate\"]\n    region = (None, None, p.faces, None)\n    p.SectionAssignment(region=region, sectionName=\"Shell\")\n\n    # Create the assembly\n    a = m.rootAssembly\n    vp.setValues(displayedObject=a)\n    a.DatumCsysByDefault(CARTESIAN)\n    a.Instance(name=\"Plate-1\", part=p, dependent=OFF)\n    pi = a.instances[\"Plate-1\"]\n\n    # Create the step\n    m.StaticStep(name=\"Step-1\", previous=\"Initial\", description=\"Apply pressure\", timePeriod=1, initialInc=1)\n    vp.assemblyDisplay.setValues(step=\"Step-1\")\n    m.fieldOutputRequests[\"F-Output-1\"].setValues(frequency=1, variables=(\"U\",))\n    m.FieldOutputRequest(name=\"F-Output-2\", createStepName=\"Step-1\", variables=(\"SF\",), position=NODES)\n    del mdb.models[\"Model-1\"].historyOutputRequests[\"H-Output-1\"]\n\n    # Create the displacement BC\n    e = pi.edges\n    edges = e.findAt(\n        ((0.25, 0.0, 0.0),),\n        ((1.0, 0.25, 0.0),),\n        ((0.75, 1.0, 0.0),),\n        ((0.0, 0.75, 0.0),),\n    )\n    region = (None, edges, None, None)\n    m.DisplacementBC(name=\"Pinned\", createStepName=\"Step-1\", region=region, u1=0.0, u2=0.0, u3=0.0)\n\n    # Create the Pressure load\n    s1 = pi.faces\n    side1Faces1 = s1.findAt(\n        (\n            (0.333333333333333, 0.333333333333333, 0.0),\n            (0.0, 0.0, 1.0),\n        ),\n    )\n    region = regionToolset.Region(side1Faces=side1Faces1)\n    m.Pressure(\n        name=\"Load-1\", createStepName=\"Step-1\", region=region, distributionType=UNIFORM, magnitude=1.0, amplitude=UNSET\n    )\n\n    # Partition the face\n    f1, e1 = pi.faces, pi.edges\n    faces = (f1.findAt(coordinates=(0.33333333333, 0.33333333333, 0.0)),)\n    pt1 = pi.InterestingPoint(edge=e1.findAt(coordinates=(0.0, 0.75, 0.0)), rule=MIDDLE)\n    pt2 = pi.InterestingPoint(edge=e1.findAt(coordinates=(1.0, 0.25, 0.0)), rule=MIDDLE)\n    a.PartitionFaceByShortestPath(faces=faces, point1=pt1, point2=pt2)\n    faces = (\n        f1.findAt(coordinates=(0.33333333333, 0.66666666667, 0.0)),\n        f1.findAt(coordinates=(0.66666666667, 0.33333333333, 0.0)),\n    )\n    pt1 = pi.InterestingPoint(edge=e1.findAt(coordinates=(0.75, 1.0, 0.0)), rule=MIDDLE)\n    pt2 = pi.InterestingPoint(edge=e1.findAt(coordinates=(0.25, 0.0, 0.0)), rule=MIDDLE)\n    a.PartitionFaceByShortestPath(faces=faces, point1=pt1, point2=pt2)\n\n    # Create the Geometry set CENTER\n    verts = pi.vertices.findAt(((0.5, 0.5, 0.0),))\n    a.Set(name=\"CENTER\", vertices=verts)\n\n    # Create the mesh\n    a.seedPartInstance(regions=(pi,), size=0.25)\n    a.generateMesh(regions=(pi,))\n\n    # Create the job\n    mdb.Job(\n        name=\"skew\",\n        model=\"Model-1\",\n        type=ANALYSIS,\n        explicitPrecision=SINGLE,\n        description=\"\",\n        userSubroutine=\"\",\n        numCpus=1,\n        scratch=\"\",\n        echoPrint=OFF,\n        modelPrint=OFF,\n        contactPrint=OFF,\n        historyPrint=OFF,\n    )\n    mdb.saveAs(pathName=\"skew.cae\")\n\n\ncreateModel()\n\n\nimport job\nimport mesh\nimport part\nfrom mesh import S4, S8R, STANDARD, STRUCTURED\n\n# Create a list of angle parameters and a list of\n# element type parameters.\n\nangles = [90, 80, 60, 40, 30]\nelemTypeCodes = [S4, S8R]\n\n# Open the model database.\nopenMdb(\"skew.cae\")\n\nmodel = mdb.models[\"Model-1\"]\npart = model.parts[\"Plate\"]\nfeature = part.features[\"Shell planar-1\"]\nassembly = model.rootAssembly\ninstance = assembly.instances[\"Plate-1\"]\njob = mdb.jobs[\"skew\"]\n\nallFaces = instance.faces\nregions = (allFaces[0], allFaces[1], allFaces[2], allFaces[3])\nassembly.setMeshControls(regions=regions, technique=STRUCTURED)\nface1 = allFaces.findAt(\n    (0.0, 0.0, 0.0),\n)\nface2 = allFaces.findAt(\n    (0.0, 1.0, 0.0),\n)\nface3 = allFaces.findAt(\n    (1.0, 1.0, 0.0),\n)\nface4 = allFaces.findAt(\n    (1.0, 0.0, 0.0),\n)\nallVertices = instance.vertices\nv1 = allVertices.findAt(\n    (0.0, 0.0, 0.0),\n)\nv2 = allVertices.findAt(\n    (0.0, 0.5, 0.0),\n)\nv3 = allVertices.findAt(\n    (0.0, 1.0, 0.0),\n)\nv4 = allVertices.findAt(\n    (0.5, 1.0, 0.0),\n)\nv5 = allVertices.findAt(\n    (1.0, 1.0, 0.0),\n)\nv6 = allVertices.findAt(\n    (1.0, 0.5, 0.0),\n)\nv7 = allVertices.findAt(\n    (1.0, 0.0, 0.0),\n)\nv8 = allVertices.findAt(\n    (0.5, 0.0, 0.0),\n)\nv9 = allVertices.findAt(\n    (0.5, 0.5, 0.0),\n)\n\n# Create a copy of the feature sketch to modify.\n\ntmpSketch = model.ConstrainedSketch(\"tmp\", feature.sketch)\nv, d = tmpSketch.vertices, tmpSketch.dimensions\n\n# Create some dictionaries to hold results. Seed the\n# dictionaries with the theoretical results.\n\ndispData, maxMomentData, minMomentData = {}, {}, {}\ndispData[\"Theoretical\"] = ((90, -0.001478), (80, -0.001409), (60, -0.000932), (40, -0.000349), (30, -0.000148))\nmaxMomentData[\"Theoretical\"] = ((90, 0.0479), (80, 0.0486), (60, 0.0425), (40, 0.0281), (30, 0.0191))\nminMomentData[\"Theoretical\"] = ((90, 0.0479), (80, 0.0448), (60, 0.0333), (40, 0.0180), (30, 0.0108))\n\n# Loop over the parameters to perform the parameter study.\n\nfor elemCode in elemTypeCodes:\n    # Convert the element type codes to strings.\n\n    elemName = repr(elemCode)\n    dispData[elemName], maxMomentData[elemName], minMomentData[elemName] = [], [], []\n\n    # Set the element type.\n\n    elemType = mesh.ElemType(elemCode=elemCode, elemLibrary=STANDARD)\n    assembly.setElementType(regions=(instance.faces,), elemTypes=(elemType,))\n\n    for angle in angles:\n        # Skew the geometry and regenerate the mesh.\n        assembly.deleteMesh(regions=(instance,))\n\n        d[0].setValues(\n            value=angle,\n        )\n        feature.setValues(sketch=tmpSketch)\n        part.regenerate()\n        assembly.regenerate()\n        assembly.setLogicalCorners(region=face1, corners=(v1, v2, v9, v8))\n        assembly.setLogicalCorners(region=face2, corners=(v2, v3, v4, v9))\n        assembly.setLogicalCorners(region=face3, corners=(v9, v4, v5, v6))\n        assembly.setLogicalCorners(region=face4, corners=(v8, v9, v6, v7))\n        assembly.generateMesh(regions=(instance,))\n\n        # Run the job, then process the results.\n\n        job.submit()\n        job.waitForCompletion()\n        print(\"Completed job for %s at %s degrees\" % (elemName, angle))\n        disp, maxMoment, minMoment = getResults()\n        dispData[elemName].append((angle, disp))\n        maxMomentData[elemName].append((angle, maxMoment))\n        minMomentData[elemName].append((angle, minMoment))\n\n# Plot the results.\n\ncreateXYPlot((10, 10), \"Skew 1\", \"Displacement - 4x4 Mesh\", dispData)\ncreateXYPlot((160, 10), \"Skew 2\", \"Max Moment - 4x4 Mesh\", maxMomentData)\ncreateXYPlot((310, 10), \"Skew 3\", \"Min Moment - 4x4 Mesh\", minMomentData)"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.4"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}