<!DOCTYPE html>
<html class="writer-html5" lang="en/html" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.18.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Reproducing the cantilever beam tutorial &mdash; abqpy 2021.5.4.post3.dev12+g26dcce5db documentation</title>
      <link rel="stylesheet" href="../../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/theme.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/togglebutton.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/copybutton.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/sphinx-codeautolink.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster.custom.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster.bundle.min.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster-sideTip-shadow.min.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster-sideTip-punk.min.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster-sideTip-noir.min.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster-sideTip-light.min.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/tooltipster-sideTip-borderless.min.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/micromodal.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/graphviz.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/sg_gallery.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/sg_gallery-binder.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/sg_gallery-dataframe.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/sg_gallery-rendered-html.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/autoclasstoc.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/css/sphinx_rtd_theme.css" type="text/css" />
      <link rel="stylesheet" href="../../_static/design-style.1e8bd061cd6da7fc9cf755528e8ffc24.min.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script src="../../_static/jquery.js"></script>
        <script src="../../_static/_sphinx_javascript_frameworks_compat.js"></script>
        <script data-url_root="../../" id="documentation_options" src="../../_static/documentation_options.js"></script>
        <script src="../../_static/doctools.js"></script>
        <script src="../../_static/sphinx_highlight.js"></script>
        <script src="../../_static/clipboard.min.js"></script>
        <script src="../../_static/copybutton.js"></script>
        <script src="../../_static/js/hoverxref.js"></script>
        <script src="../../_static/js/tooltipster.bundle.min.js"></script>
        <script src="../../_static/js/micromodal.min.js"></script>
        <script>let toggleHintShow = 'Click to show';</script>
        <script>let toggleHintHide = 'Click to hide';</script>
        <script>let toggleOpenOnPrint = 'true';</script>
        <script src="../../_static/togglebutton.js"></script>
        <script kind="utterances">

    var commentsRunWhenDOMLoaded = cb => {
    if (document.readyState != 'loading') {
        cb()
    } else if (document.addEventListener) {
        document.addEventListener('DOMContentLoaded', cb)
    } else {
        document.attachEvent('onreadystatechange', function() {
        if (document.readyState == 'complete') cb()
        })
    }
}

var addUtterances = () => {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://utteranc.es/client.js";
    script.async = "async";

    script.setAttribute("repo", "haiiliin/abqpy");
    script.setAttribute("issue-term", "pathname");
    script.setAttribute("theme", "github-light");
    script.setAttribute("label", "üí¨ comment");
    script.setAttribute("crossorigin", "anonymous");

    sections = document.querySelectorAll("div.section");
    if (sections !== null) {
        section = sections[sections.length-1];
        section.appendChild(script);
    }
}
commentsRunWhenDOMLoaded(addUtterances);
</script>
        <script>var togglebuttonSelector = '.toggle, .admonition.dropdown';</script>
        <script src="../../_static/design-tabs.js"></script>
        <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="../../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../../genindex.html" />
    <link rel="search" title="Search" href="../../search.html" />
    <link rel="next" title="Generating a customized plot" href="plot.html" />
    <link rel="prev" title="Putting it all Together: Abaqus Scripting Interface Examples" href="index.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >

          
          
          <a href="../../index.html" class="icon icon-home">
            abqpy
          </a>
              <div class="version">
                true
              </div>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <p class="caption" role="heading"><span class="caption-text">User Manual</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../getting_started.html">Getting Started</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../envvars.html">Environment Variables</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../cli.html">Command Line Interface</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Tutorials &amp; Examples</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../tutorials.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../examples/index.html">Examples</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">References</span></p>
<ul class="current">
<li class="toctree-l1 current"><a class="reference internal" href="../index.html">Abaqus Scripting User's Guide</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="../about/index.html">About the Abaqus Scripting Interface</a></li>
<li class="toctree-l2"><a class="reference internal" href="../python/index.html">Using the Abaqus Scripting Interface</a></li>
<li class="toctree-l2"><a class="reference internal" href="../environment/index.html">The Abaqus Python Development Environment</a></li>
<li class="toctree-l2 current"><a class="reference internal" href="index.html">Putting it all Together: Abaqus Scripting Interface Examples</a><ul class="current">
<li class="toctree-l3 current"><a class="current reference internal" href="#">Reproducing the cantilever beam tutorial</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#about-the-cantilever-beam-example">About the cantilever beam example</a></li>
<li class="toctree-l4"><a class="reference internal" href="#running-the-example">Running the example</a></li>
<li class="toctree-l4"><a class="reference internal" href="#the-cantilever-beam-example-script">The cantilever beam example script</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="plot.html">Generating a customized plot</a></li>
<li class="toctree-l3"><a class="reference internal" href="sensitivity.html">Investigating the skew sensitivity of shell elements</a></li>
<li class="toctree-l3"><a class="reference internal" href="settings.html">Editing display preferences and GUI settings</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="../output/index.html">Accessing an Output Database</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../../reference/index.html">Abaqus Class References</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../CHANGES.html">Abaqus API Changes</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../autoapi/index.html">Abqpy API Reference</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../localization.html">Documentation Localization</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Project Links</span></p>
<ul>
<li class="toctree-l1"><a class="reference external" href="https://github.com/haiiliin/abqpy">GitHub</a></li>
<li class="toctree-l1"><a class="reference external" href="https://pypi.org/project/abqpy">PyPI</a></li>
<li class="toctree-l1"><a class="reference external" href="https://readthedocs.org/projects/abqpy">Read the Docs</a></li>
<li class="toctree-l1"><a class="reference external" href="https://github.com/haiiliin/abqpy/issues">Bug Report</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">External Links</span></p>
<ul>
<li class="toctree-l1"><a class="reference external" href="https://www.3ds.com/">Dassault Syst√®mes</a></li>
<li class="toctree-l1"><a class="reference external" href="https://help.3ds.com/2023/English/DSSIMULIA_Established/SIMULIA_Established_FrontmatterMap/DSDocHome.htm?contextscope=all">SIMULA User Assistance</a></li>
<li class="toctree-l1"><a class="reference external" href="https://www.3ds.com/products-services/simulia/products/abaqus/">Abaqus FEA</a></li>
</ul>
<p class="caption" role="heading"><span class="caption-text">Policy &amp; License</span></p>
<ul>
<li class="toctree-l1"><a class="reference internal" href="../../policy.html">Comment Policy</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../index.html">abqpy</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../../index.html" class="icon icon-home" aria-label="Home"></a></li>
          <li class="breadcrumb-item"><a href="../index.html">Abaqus Scripting User's Guide</a></li>
          <li class="breadcrumb-item"><a href="index.html">Putting it all Together: Abaqus Scripting Interface Examples</a></li>
      <li class="breadcrumb-item active">Reproducing the cantilever beam tutorial</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../../_sources/user/examples/cantilever.md.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="reproducing-the-cantilever-beam-tutorial">
<h1>Reproducing the cantilever beam tutorial<a class="headerlink" href="#reproducing-the-cantilever-beam-tutorial" title="Permalink to this heading">ÔÉÅ</a></h1>
<p>This section explains how to use the Abaqus Scripting Interface commands to reproduce a tutorial that shows the basic steps to create and analyze a simple model. The tutorial, <a class="reference external" href="https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEGSARefMap/simagsa-m-Caebeam-sb.htm?contextscope=all#simagsa-m-Caebeam-sb">Creating and Analyzing a Simple Model in Abaqus/CAE</a>, is available in <a class="reference external" href="https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEGSARefMap/simagsa-c-ov.htm?contextscope=all#simagsa-c-ov">Getting Started with Abaqus/CAE</a>.</p>
<section id="about-the-cantilever-beam-example">
<h2>About the cantilever beam example<a class="headerlink" href="#about-the-cantilever-beam-example" title="Permalink to this heading">ÔÉÅ</a></h2>
<p>The example leads you through the Abaqus/CAE modeling process by visiting each of the modules and shows you the basic steps to create and analyze a simple model. In <a class="reference external" href="https://help.3ds.com/2021/English/DSSIMULIA_Established/SIMACAEGSARefMap/simagsa-m-Caebeam-sb.htm?contextscope=all#simagsa-m-Caebeam-sb">Creating and Analyzing a Simple Model in Abaqus/CAE</a>, you create a model of a steel cantilever beam and load its top surface. You then analyze the beam and plot the resulting stresses and displacements. <a class="hxr-hoverxref hxr-tooltip reference internal" href="#gst-beam"><span class="std std-numref">Fig. 22</span></a> illustrates the model that you create and analyze.</p>
<figure class="align-center" id="id1">
<span id="gst-beam"></span><a class="reference internal image-reference" href="../../_images/gst-beam.png"><img alt="../../_images/gst-beam.png" src="../../_images/gst-beam.png" style="width: 100%;" /></a>
<figcaption>
<p><span class="caption-number">Fig. 22 </span><span class="caption-text">A loaded cantilever beam.</span><a class="headerlink" href="#id1" title="Permalink to this image">ÔÉÅ</a></p>
</figcaption>
</figure>
</section>
<section id="running-the-example">
<h2>Running the example<a class="headerlink" href="#running-the-example" title="Permalink to this heading">ÔÉÅ</a></h2>
<p>Use the following command to retrieve the output database that is read by the scripts:</p>
<div class="highlight-sh notranslate"><div class="highlight"><pre><span></span>abaqus<span class="w"> </span>fetch<span class="w"> </span><span class="nv">job</span><span class="o">=</span>beamExample
</pre></div>
</div>
<p>To run the script, do the following:</p>
<ol class="arabic simple">
<li><p>Start Abaqus/CAE from a directory in which you have write permission by typing <code class="docutils literal notranslate"><span class="pre">abaqus</span> <span class="pre">cae</span></code>.</p></li>
<li><p>From the startup screen, select <strong>Run Script</strong>.</p></li>
<li><p>From the <strong>Run Script</strong> dialog box that appears, enter the path given above and select the file containing the script.</p></li>
<li><p>Click <strong>OK</strong> to run the script.</p></li>
</ol>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If Abaqus/CAE is already running, you can run the script by selecting <strong>File -&gt; Run Script</strong> from the main menu bar.</p>
</div>
</section>
<section id="the-cantilever-beam-example-script">
<h2>The cantilever beam example script<a class="headerlink" href="#the-cantilever-beam-example-script" title="Permalink to this heading">ÔÉÅ</a></h2>
<p>The first line of the script, <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">abaqus</span> <span class="pre">import</span> <span class="pre">*</span></code>, imports the Mdb and Session objects. The current viewport is <code class="docutils literal notranslate"><span class="pre">session.viewports['Viewport:</span> <span class="pre">1']</span></code>, and the current model is <code class="docutils literal notranslate"><span class="pre">mdb.models['Model-1']</span></code>. Both of these objects are available to the script after you import the <code class="docutils literal notranslate"><span class="pre">abaqus</span></code> module. The second line of the script, <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">abaqusConstants</span> <span class="pre">import</span> <span class="pre">*</span></code>, imports the Symbolic Constants defined in the Abaqus Scripting Interface. The script then creates a new model that will contain the cantilever beam example and creates a new viewport in which to display the model and the results of the analysis. For a description of the commands used in this section, see the appropriate sections in the <a class="reference internal" href="../../reference/index.html"><span class="doc">Abaqus Class References</span></a>.</p>
<p>The script then imports the <code class="docutils literal notranslate"><span class="pre">Part</span></code> module. Most of the sections in this example begin with importing the appropriate module, which illustrates how a script can import a module at any time to extend or augment the object model. However, the Abaqus Scripting Interface has a convention that all the required modules are imported at the start of a script; and that convention is followed in other example scripts in this guide.</p>
<div class="highlight-python2 notranslate"><div class="highlight"><pre><span></span><span class="sd">&quot;&quot;&quot;</span>
<span class="sd">beamExample.py</span>

<span class="sd">Reproduce the cantilever beam example from the</span>
<span class="sd">Appendix of the Getting Started with</span>
<span class="sd">Abaqus: Interactive Edition Manual.</span>
<span class="sd">&quot;&quot;&quot;</span>

<span class="kn">from</span> <span class="nn">abaqus</span> <span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span> <span class="nn">abaqusConstants</span> <span class="kn">import</span> <span class="o">*</span>
<span class="n">backwardCompatibility</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">includeDeprecated</span><span class="o">=</span><span class="bp">True</span><span class="p">,</span>
                                <span class="n">reportDeprecated</span><span class="o">=</span><span class="bp">False</span><span class="p">)</span>

<span class="c1"># Create a model.</span>

<span class="n">myModel</span> <span class="o">=</span> <span class="n">mdb</span><span class="o">.</span><span class="n">Model</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Beam&#39;</span><span class="p">)</span>

<span class="c1"># Create a new viewport in which to display the model</span>
<span class="c1"># and the results of the analysis.</span>

<span class="n">myViewport</span> <span class="o">=</span> <span class="n">session</span><span class="o">.</span><span class="n">Viewport</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Cantilever Beam Example&#39;</span><span class="p">,</span>
    <span class="n">origin</span><span class="o">=</span><span class="p">(</span><span class="mi">20</span><span class="p">,</span> <span class="mi">20</span><span class="p">),</span> <span class="n">width</span><span class="o">=</span><span class="mi">150</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">120</span><span class="p">)</span>

<span class="c1">#-----------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">part</span>

<span class="c1"># Create a sketch for the base feature.</span>

<span class="n">mySketch</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">ConstrainedSketch</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;beamProfile&#39;</span><span class="p">,</span>
    <span class="n">sheetSize</span><span class="o">=</span><span class="mf">250.</span><span class="p">)</span>

<span class="c1"># Create the rectangle.</span>

<span class="n">mySketch</span><span class="o">.</span><span class="n">rectangle</span><span class="p">(</span><span class="n">point1</span><span class="o">=</span><span class="p">(</span><span class="o">-</span><span class="mi">100</span><span class="p">,</span><span class="mi">10</span><span class="p">),</span> <span class="n">point2</span><span class="o">=</span><span class="p">(</span><span class="mi">100</span><span class="p">,</span><span class="o">-</span><span class="mi">10</span><span class="p">))</span>

<span class="c1"># Create a three-dimensional, deformable part.</span>

<span class="n">myBeam</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">Part</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Beam&#39;</span><span class="p">,</span> <span class="n">dimensionality</span><span class="o">=</span><span class="n">THREE_D</span><span class="p">,</span>
    <span class="nb">type</span><span class="o">=</span><span class="n">DEFORMABLE_BODY</span><span class="p">)</span>

<span class="c1"># Create the part&#39;s base feature by extruding the sketch</span>
<span class="c1"># through a distance of 25.0.</span>

<span class="n">myBeam</span><span class="o">.</span><span class="n">BaseSolidExtrude</span><span class="p">(</span><span class="n">sketch</span><span class="o">=</span><span class="n">mySketch</span><span class="p">,</span> <span class="n">depth</span><span class="o">=</span><span class="mf">25.0</span><span class="p">)</span>

<span class="c1">#-----------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">material</span>

<span class="c1"># Create a material.</span>

<span class="n">mySteel</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">Material</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Steel&#39;</span><span class="p">)</span>

<span class="c1"># Create the elastic properties: youngsModulus is 209.E3</span>
<span class="c1"># and poissonsRatio is 0.3</span>

<span class="n">elasticProperties</span> <span class="o">=</span> <span class="p">(</span><span class="mf">209.E3</span><span class="p">,</span> <span class="mf">0.3</span><span class="p">)</span>
<span class="n">mySteel</span><span class="o">.</span><span class="n">Elastic</span><span class="p">(</span><span class="n">table</span><span class="o">=</span><span class="p">(</span><span class="n">elasticProperties</span><span class="p">,</span> <span class="p">)</span> <span class="p">)</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">section</span>

<span class="c1"># Create the solid section.</span>

<span class="n">mySection</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">HomogeneousSolidSection</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;beamSection&#39;</span><span class="p">,</span>
    <span class="n">material</span><span class="o">=</span><span class="s1">&#39;Steel&#39;</span><span class="p">,</span> <span class="n">thickness</span><span class="o">=</span><span class="mf">1.0</span><span class="p">)</span>

<span class="c1"># Assign the section to the region. The region refers</span>
<span class="c1"># to the single cell in this model.</span>

<span class="n">region</span> <span class="o">=</span> <span class="p">(</span><span class="n">myBeam</span><span class="o">.</span><span class="n">cells</span><span class="p">,)</span>
<span class="n">myBeam</span><span class="o">.</span><span class="n">SectionAssignment</span><span class="p">(</span><span class="n">region</span><span class="o">=</span><span class="n">region</span><span class="p">,</span>
    <span class="n">sectionName</span><span class="o">=</span><span class="s1">&#39;beamSection&#39;</span><span class="p">)</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">assembly</span>

<span class="c1"># Create a part instance.</span>

<span class="n">myAssembly</span> <span class="o">=</span> <span class="n">myModel</span><span class="o">.</span><span class="n">rootAssembly</span>
<span class="n">myInstance</span> <span class="o">=</span> <span class="n">myAssembly</span><span class="o">.</span><span class="n">Instance</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;beamInstance&#39;</span><span class="p">,</span>
    <span class="n">part</span><span class="o">=</span><span class="n">myBeam</span><span class="p">,</span> <span class="n">dependent</span><span class="o">=</span><span class="n">OFF</span><span class="p">)</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">step</span>

<span class="c1"># Create a step. The time period of the static step is 1.0,</span>
<span class="c1"># and the initial incrementation is 0.1; the step is created</span>
<span class="c1"># after the initial step.</span>

<span class="n">myModel</span><span class="o">.</span><span class="n">StaticStep</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;beamLoad&#39;</span><span class="p">,</span> <span class="n">previous</span><span class="o">=</span><span class="s1">&#39;Initial&#39;</span><span class="p">,</span>
    <span class="n">timePeriod</span><span class="o">=</span><span class="mf">1.0</span><span class="p">,</span> <span class="n">initialInc</span><span class="o">=</span><span class="mf">0.1</span><span class="p">,</span>
    <span class="n">description</span><span class="o">=</span><span class="s1">&#39;Load the top of the beam.&#39;</span><span class="p">)</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">load</span>

<span class="c1"># Find the end face using coordinates.</span>

<span class="n">endFaceCenter</span> <span class="o">=</span> <span class="p">(</span><span class="o">-</span><span class="mi">100</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mf">12.5</span><span class="p">)</span>
<span class="n">endFace</span> <span class="o">=</span> <span class="n">myInstance</span><span class="o">.</span><span class="n">faces</span><span class="o">.</span><span class="n">findAt</span><span class="p">((</span><span class="n">endFaceCenter</span><span class="p">,)</span> <span class="p">)</span>

<span class="c1"># Create a boundary condition that encastres one end</span>
<span class="c1"># of the beam.</span>

<span class="n">endRegion</span> <span class="o">=</span> <span class="p">(</span><span class="n">endFace</span><span class="p">,)</span>
<span class="n">myModel</span><span class="o">.</span><span class="n">EncastreBC</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Fixed&#39;</span><span class="p">,</span><span class="n">createStepName</span><span class="o">=</span><span class="s1">&#39;beamLoad&#39;</span><span class="p">,</span>
    <span class="n">region</span><span class="o">=</span><span class="n">endRegion</span><span class="p">)</span>

<span class="c1"># Find the top face using coordinates.</span>

<span class="n">topFaceCenter</span> <span class="o">=</span> <span class="p">(</span><span class="mi">0</span><span class="p">,</span><span class="mi">10</span><span class="p">,</span><span class="mf">12.5</span><span class="p">)</span>
<span class="n">topFace</span> <span class="o">=</span> <span class="n">myInstance</span><span class="o">.</span><span class="n">faces</span><span class="o">.</span><span class="n">findAt</span><span class="p">((</span><span class="n">topFaceCenter</span><span class="p">,)</span> <span class="p">)</span>

<span class="c1"># Create a pressure load on the top face of the beam.</span>

<span class="n">topSurface</span> <span class="o">=</span> <span class="p">((</span><span class="n">topFace</span><span class="p">,</span> <span class="n">SIDE1</span><span class="p">),</span> <span class="p">)</span>
<span class="n">myModel</span><span class="o">.</span><span class="n">Pressure</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="s1">&#39;Pressure&#39;</span><span class="p">,</span> <span class="n">createStepName</span><span class="o">=</span><span class="s1">&#39;beamLoad&#39;</span><span class="p">,</span>
    <span class="n">region</span><span class="o">=</span><span class="n">topSurface</span><span class="p">,</span> <span class="n">magnitude</span><span class="o">=</span><span class="mf">0.5</span><span class="p">)</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">mesh</span>

<span class="c1"># Assign an element type to the part instance.</span>

<span class="n">region</span> <span class="o">=</span> <span class="p">(</span><span class="n">myInstance</span><span class="o">.</span><span class="n">cells</span><span class="p">,)</span>
<span class="n">elemType</span> <span class="o">=</span> <span class="n">mesh</span><span class="o">.</span><span class="n">ElemType</span><span class="p">(</span><span class="n">elemCode</span><span class="o">=</span><span class="n">C3D8I</span><span class="p">,</span> <span class="n">elemLibrary</span><span class="o">=</span><span class="n">STANDARD</span><span class="p">)</span>
<span class="n">myAssembly</span><span class="o">.</span><span class="n">setElementType</span><span class="p">(</span><span class="n">regions</span><span class="o">=</span><span class="n">region</span><span class="p">,</span> <span class="n">elemTypes</span><span class="o">=</span><span class="p">(</span><span class="n">elemType</span><span class="p">,))</span>

<span class="c1"># Seed the part instance.</span>

<span class="n">myAssembly</span><span class="o">.</span><span class="n">seedPartInstance</span><span class="p">(</span><span class="n">regions</span><span class="o">=</span><span class="p">(</span><span class="n">myInstance</span><span class="p">,),</span> <span class="n">size</span><span class="o">=</span><span class="mf">10.0</span><span class="p">)</span>

<span class="c1"># Mesh the part instance.</span>

<span class="n">myAssembly</span><span class="o">.</span><span class="n">generateMesh</span><span class="p">(</span><span class="n">regions</span><span class="o">=</span><span class="p">(</span><span class="n">myInstance</span><span class="p">,))</span>

<span class="c1"># Display the meshed beam.</span>

<span class="n">myViewport</span><span class="o">.</span><span class="n">assemblyDisplay</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">mesh</span><span class="o">=</span><span class="n">ON</span><span class="p">)</span>
<span class="n">myViewport</span><span class="o">.</span><span class="n">assemblyDisplay</span><span class="o">.</span><span class="n">meshOptions</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">meshTechnique</span><span class="o">=</span><span class="n">ON</span><span class="p">)</span>
<span class="n">myViewport</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">displayedObject</span><span class="o">=</span><span class="n">myAssembly</span><span class="p">)</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">job</span>

<span class="c1"># Create an analysis job for the model and submit it.</span>

<span class="n">jobName</span> <span class="o">=</span> <span class="s1">&#39;beam_tutorial&#39;</span>
<span class="n">myJob</span> <span class="o">=</span> <span class="n">mdb</span><span class="o">.</span><span class="n">Job</span><span class="p">(</span><span class="n">name</span><span class="o">=</span><span class="n">jobName</span><span class="p">,</span> <span class="n">model</span><span class="o">=</span><span class="s1">&#39;Beam&#39;</span><span class="p">,</span>
    <span class="n">description</span><span class="o">=</span><span class="s1">&#39;Cantilever beam tutorial&#39;</span><span class="p">)</span>

<span class="c1"># Wait for the job to complete.</span>

<span class="n">myJob</span><span class="o">.</span><span class="n">submit</span><span class="p">()</span>
<span class="n">myJob</span><span class="o">.</span><span class="n">waitForCompletion</span><span class="p">()</span>

<span class="c1">#-------------------------------------------------------</span>

<span class="kn">import</span> <span class="nn">visualization</span>

<span class="c1"># Open the output database and display a</span>
<span class="c1"># default contour plot.</span>

<span class="n">myOdb</span> <span class="o">=</span> <span class="n">visualization</span><span class="o">.</span><span class="n">openOdb</span><span class="p">(</span><span class="n">path</span><span class="o">=</span><span class="n">jobName</span> <span class="o">+</span> <span class="s1">&#39;.odb&#39;</span><span class="p">)</span>
<span class="n">myViewport</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">displayedObject</span><span class="o">=</span><span class="n">myOdb</span><span class="p">)</span>
<span class="n">myViewport</span><span class="o">.</span><span class="n">odbDisplay</span><span class="o">.</span><span class="n">display</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">plotState</span><span class="o">=</span><span class="n">CONTOURS_ON_DEF</span><span class="p">)</span>

<span class="n">myViewport</span><span class="o">.</span><span class="n">odbDisplay</span><span class="o">.</span><span class="n">commonOptions</span><span class="o">.</span><span class="n">setValues</span><span class="p">(</span><span class="n">renderStyle</span><span class="o">=</span><span class="n">FILLED</span><span class="p">)</span>
</pre></div>
</div>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="index.html" class="btn btn-neutral float-left" title="Putting it all Together: Abaqus Scripting Interface Examples" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="plot.html" class="btn btn-neutral float-right" title="Generating a customized plot" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, WANG Hailin.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
   
<div
  class="rst-versions"
  data-toggle="rst-versions"
  role="note"
  aria-label="versions"
>
  <span class="rst-current-version" data-toggle="rst-current-version">
    <span class="fa fa-book"> Read the Docs</span>
    v: true
    <span class="fa fa-caret-down"></span>
  </span>
  <div class="rst-other-versions">
    
    <dl>
      <dt>Languages</dt>
       
      <strong>
        
        <dd><a href="/abqpy/en/true/">en</a></dd>
        
      </strong>
        
        <dd><a href="/abqpy/zh_CN/true/">zh_CN</a></dd>
         
    </dl>
     
    <dl>
      <dt>Versions</dt>
       
        <dd><a href="/abqpy/en/2016/">2016</a></dd>
          
        <dd><a href="/abqpy/en/2017/">2017</a></dd>
          
        <dd><a href="/abqpy/en/2018/">2018</a></dd>
          
        <dd><a href="/abqpy/en/2019/">2019</a></dd>
          
        <dd><a href="/abqpy/en/2020/">2020</a></dd>
          
        <dd><a href="/abqpy/en/2021/">2021</a></dd>
          
        <dd><a href="/abqpy/en/2022/">2022</a></dd>
          
        <dd><a href="/abqpy/en/2023/">2023</a></dd>
          
        <dd><a href="/abqpy/en/latest/">latest</a></dd>
          
        <dd><a href="/abqpy/en/sphinx-book-theme/">sphinx-book-theme</a></dd>
          
        <dd><a href="/abqpy/en/furo/">furo</a></dd>
         
    </dl>
     
    <dl>
      <dt>Downloads</dt>
      
      <dd><a href="/abqpy/en/true/abqpy-docs-en-true.pdf">pdf</a></dd>
      
      <dd><a href="/abqpy/en/true/abqpy-docs-en-true.epub">epub</a></dd>
      
    </dl>
     
    <hr />
    <a
      href="https://tech.michaelaltfield.net/2020/07/18/sphinx-rtd-github-pages-1/"
      >Continuous Documentation</a
    >
    hosting provided by <a href="https://pages.github.com/">GitHub Pages</a>.
  </div>
</div>
<script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>