# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2022, WANG Hailin
# This file is distributed under the same license as the abqpy package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: abqpy 2020.3.3 (dev)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-09-17 00:14+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../summary/mdb/model/property.rst:3
msgid "Property"
msgstr ""

#: ../../summary/mdb/model/property.rst:5
msgid "The Property commands are used to create and manage reinforcements and to assign properties to a part. (See also Material commands and Section commands.) The Property commands are methods of a Part object."
msgstr ""

#: ../../summary/mdb/model/property.rst:9
msgid "Create properties for Part"
msgstr ""

#: ../../../../src/abaqus/Property/PropertyPart.py:docstring of abaqus.Property.PropertyPart.PropertyPart:0
msgid "Public Data Attributes:"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`geometryValidity <abaqus.Property.PropertyPart.PropertyPart.geometryValidity>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A Boolean specifying the validity of the geometry of the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`isOutOfDate <abaqus.Property.PropertyPart.PropertyPart.isOutOfDate>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "An Int specifying that feature parameters have been modified but that the part has not been regenerated."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`timeStamp <abaqus.Property.PropertyPart.PropertyPart.timeStamp>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A Float specifying when the part was last modified."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`vertices <abaqus.Property.PropertyPart.PropertyPart.vertices>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.BasicGeometry.VertexArray.VertexArray` object specifying all the vertices in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`ignoredVertices <abaqus.Property.PropertyPart.PropertyPart.ignoredVertices>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "An :py:class:`~abaqus.BasicGeometry.IgnoredVertexArray.IgnoredVertexArray` object specifying all the ignored vertices in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`edges <abaqus.Property.PropertyPart.PropertyPart.edges>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "An :py:class:`~abaqus.BasicGeometry.EdgeArray.EdgeArray` object specifying all the edges in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`ignoredEdges <abaqus.Property.PropertyPart.PropertyPart.ignoredEdges>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "An :py:class:`~abaqus.BasicGeometry.IgnoredEdgeArray.IgnoredEdgeArray` object specifying all the ignored edges in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`faces <abaqus.Property.PropertyPart.PropertyPart.faces>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.BasicGeometry.FaceArray.FaceArray` object specifying all the faces in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`cells <abaqus.Property.PropertyPart.PropertyPart.cells>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.BasicGeometry.CellArray.CellArray` object specifying all the cells in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`features <abaqus.Property.PropertyPart.PropertyPart.features>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Feature objects specifying all the features in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`featuresById <abaqus.Property.PropertyPart.PropertyPart.featuresById>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Feature objects specifying all Feature objects in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`datums <abaqus.Property.PropertyPart.PropertyPart.datums>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Datum objects specifying all the datums in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`elements <abaqus.Property.PropertyPart.PropertyPart.elements>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Mesh.MeshElementArray.MeshElementArray` object specifying all the elements in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`elemFaces <abaqus.Property.PropertyPart.PropertyPart.elemFaces>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of MeshFace objects specifying all the element faces in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`elementFaces <abaqus.Property.PropertyPart.PropertyPart.elementFaces>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Mesh.MeshFaceArray.MeshFaceArray` object specifying all the unique element faces in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`nodes <abaqus.Property.PropertyPart.PropertyPart.nodes>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Mesh.MeshNodeArray.MeshNodeArray` object specifying all the nodes in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`retainedNodes <abaqus.Property.PropertyPart.PropertyPart.retainedNodes>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Mesh.MeshNodeArray.MeshNodeArray` object specifying all the retained nodes in the substructure part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`sets <abaqus.Property.PropertyPart.PropertyPart.sets>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Set objects specifying for more information, see Set."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`allSets <abaqus.Property.PropertyPart.PropertyPart.allSets>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Set objects specifying the contents of the **allSets** repository is the same as the contents of the **sets** repository."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`allInternalSets <abaqus.Property.PropertyPart.PropertyPart.allInternalSets>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Set objects specifying picked regions."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`surfaces <abaqus.Property.PropertyPart.PropertyPart.surfaces>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Surface objects specifying for more information, see Surface."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`allSurfaces <abaqus.Property.PropertyPart.PropertyPart.allSurfaces>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Surface objects specifying the contents of the **allSurfaces** repository is the same as the contents of the **surfaces** repository."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`allInternalSurfaces <abaqus.Property.PropertyPart.PropertyPart.allInternalSurfaces>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Surface objects specifying picked regions."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`skins <abaqus.Property.PropertyPart.PropertyPart.skins>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Skin objects specifying the skins created on the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`stringers <abaqus.Property.PropertyPart.PropertyPart.stringers>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of Stringer objects specifying the stringers created on the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`referencePoints <abaqus.Property.PropertyPart.PropertyPart.referencePoints>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of ReferencePoint objects."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`engineeringFeatures <abaqus.Property.PropertyPart.PropertyPart.engineeringFeatures>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "An :py:class:`~abaqus.EngineeringFeature.EngineeringFeature.EngineeringFeature` object."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`sectionAssignments <abaqus.Property.PropertyPart.PropertyPart.sectionAssignments>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Property.SectionAssignmentArray.SectionAssignmentArray` object."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`materialOrientations <abaqus.Property.PropertyPart.PropertyPart.materialOrientations>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Property.MaterialOrientationArray.MaterialOrientationArray` object."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`compositeLayups <abaqus.Property.PropertyPart.PropertyPart.compositeLayups>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of CompositeLayup objects."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`elemEdges <abaqus.Property.PropertyPart.PropertyPart.elemEdges>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A repository of MeshEdge objects specifying all the element edges in the part."
msgstr ""

#: ../../None:34:<autosummary>:1
msgid ":py:obj:`elementEdges <abaqus.Property.PropertyPart.PropertyPart.elementEdges>`\\"
msgstr ""

#: ../../None:34:<autosummary>:1
msgid "A :py:class:`~abaqus.Mesh.MeshEdgeArray.MeshEdgeArray` object specifying all the unique element edges in the part."
msgstr ""

#: ../../None:4:<autosummary>:1
msgid ":py:obj:`name <abaqus.Property.PropertyPart.PropertyPart.name>`\\"
msgstr ""

#: ../../None:4:<autosummary>:1
msgid "A String specifying the repository key."
msgstr ""

#: ../../None:4:<autosummary>:1
msgid ":py:obj:`id <abaqus.Property.PropertyPart.PropertyPart.id>`\\"
msgstr ""

#: ../../None:4:<autosummary>:1
msgid "An Int specifying the ID of the feature."
msgstr ""

#: ../../../../src/abaqus/Property/PropertyPart.py:docstring of abaqus.Property.PropertyPart.PropertyPart:0
msgid "Public Methods:"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`CompositeLayup <abaqus.Property.PropertyPart.PropertyPart.CompositeLayup>`\\ \\(name\\[\\, description\\, ...\\]\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method creates a CompositeLayup object."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`SectionAssignment <abaqus.Property.PropertyPart.PropertyPart.SectionAssignment>`\\ \\(region\\, sectionName\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method creates a SectionAssignment object."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`MaterialOrientation <abaqus.Property.PropertyPart.PropertyPart.MaterialOrientation>`\\ \\(\\[region\\, localCsys\\, ...\\]\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method creates a MaterialOrientation object."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`assignBeamSectionOrientation <abaqus.Property.PropertyPart.PropertyPart.assignBeamSectionOrientation>`\\ \\(region\\, method\\, n1\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method assigns a beam section orientation to a region of a part."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`assignMaterialOrientation <abaqus.Property.PropertyPart.PropertyPart.assignMaterialOrientation>`\\ \\(region\\, localCsys\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method assigns a material orientation to a region."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`assignRebarOrientation <abaqus.Property.PropertyPart.PropertyPart.assignRebarOrientation>`\\ \\(region\\, localCsys\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method assigns a rebar reference orientation to a region."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`flipNormal <abaqus.Property.PropertyPart.PropertyPart.flipNormal>`\\ \\(regions\\[\\, referenceRegion\\]\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method flips the normals of shell or membrane elements of an orphan mesh or of two-dimensional geometric regions."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`flipTangent <abaqus.Property.PropertyPart.PropertyPart.flipTangent>`\\ \\(regions\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method flips the tangents of beam or truss elements of an orphan mesh or of one-dimensional geometric regions."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`unassignBeamSectionOrientation <abaqus.Property.PropertyPart.PropertyPart.unassignBeamSectionOrientation>`\\ \\(index\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method deletes a beam section orientation assignment."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`unassignMaterialOrientation <abaqus.Property.PropertyPart.PropertyPart.unassignMaterialOrientation>`\\ \\(index\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method deletes a material orientation assignment."
msgstr ""

#: ../../None:13:<autosummary>:1
msgid ":py:obj:`unassignRebarOrientation <abaqus.Property.PropertyPart.PropertyPart.unassignRebarOrientation>`\\ \\(index\\)"
msgstr ""

#: ../../None:13:<autosummary>:1
msgid "This method deletes a rebar orientation assignment."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`__init__ <abaqus.Property.PropertyPart.PropertyPart.__init__>`\\ \\(\\*args\\, \\*\\*kwargs\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromBooleanCut <abaqus.Property.PropertyPart.PropertyPart.PartFromBooleanCut>`\\ \\(name\\, instanceToBeCut\\, ...\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part in the parts repository after subtracting or cutting the geometries of a group of part instances from that of a base part instance."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromBooleanMerge <abaqus.Property.PropertyPart.PropertyPart.PartFromBooleanMerge>`\\ \\(name\\, instances\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part in the parts repository after merging two or more part instances."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromExtrude2DMesh <abaqus.Property.PropertyPart.PropertyPart.PartFromExtrude2DMesh>`\\ \\(name\\, part\\, depth\\, ...\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object by extruding an existing two-dimensional orphan mesh Part object in the positive **Z**-direction and places it in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromGeometryFile <abaqus.Property.PropertyPart.PropertyPart.PartFromGeometryFile>`\\ \\(name\\, geometryFile\\, ...\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object and places it in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromInstanceMesh <abaqus.Property.PropertyPart.PropertyPart.PartFromInstanceMesh>`\\ \\(name\\[\\, partInstances\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object containing the mesh found in the supplied PartInstance objects and places the new Part object in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromMesh <abaqus.Property.PropertyPart.PropertyPart.PartFromMesh>`\\ \\(name\\[\\, copySets\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object containing the mesh found in the part and places the new Part object in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromMeshMirror <abaqus.Property.PropertyPart.PropertyPart.PartFromMeshMirror>`\\ \\(name\\, part\\, point1\\, point2\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object by mirroring an existing orphan mesh Part object about a specified plane and places it in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromNodesAndElements <abaqus.Property.PropertyPart.PropertyPart.PartFromNodesAndElements>`\\ \\(name\\, ...\\[\\, twist\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object from nodes and elements and places it in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromOdb <abaqus.Property.PropertyPart.PropertyPart.PartFromOdb>`\\ \\(name\\, odb\\[\\, fileName\\, instance\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates an orphan mesh Part object by reading an output database."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromSection3DMeshByPlane <abaqus.Property.PropertyPart.PropertyPart.PartFromSection3DMeshByPlane>`\\ \\(name\\, part\\, ...\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a Part object by cutting an existing three-dimensional orphan mesh Part object by a plane and places it in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`PartFromSubstructure <abaqus.Property.PropertyPart.PropertyPart.PartFromSubstructure>`\\ \\(name\\, substructureFile\\, ...\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a substructure Part object by reading a substructure sim file and places it in the parts repository."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`Part2DGeomFrom2DMesh <abaqus.Property.PropertyPart.PropertyPart.Part2DGeomFrom2DMesh>`\\ \\(name\\, part\\, featureAngle\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method creates a geometric Part object from the outline of an existing two-dimensional orphan mesh Part object and places it in the parts repository."
msgstr ""

#: ../../None:65:<autosummary>:1
#: ../../None:68:<autosummary>:1
msgid ":py:obj:`setValues <abaqus.Property.PropertyPart.PropertyPart.setValues>`\\ \\(\\*args\\, \\*\\*kwargs\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
#: ../../None:68:<autosummary>:1
msgid "This method modifies the Part object."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`addGeomToSketch <abaqus.Property.PropertyPart.PropertyPart.addGeomToSketch>`\\ \\(sketch\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method converts a part into a sketch by projecting all of the edges of the part onto the X-Y plane of the sketch."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`assignThickness <abaqus.Property.PropertyPart.PropertyPart.assignThickness>`\\ \\(faces\\[\\, thickness\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method assigns thickness data to shell faces."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`backup <abaqus.Property.PropertyPart.PropertyPart.backup>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method makes a backup copy of the features in the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`checkGeometry <abaqus.Property.PropertyPart.PropertyPart.checkGeometry>`\\ \\(\\[detailed\\, reportFacetErrors\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method checks the validity of the geometry of the part and prints a count of all topological entities on the part (faces, edges, vertices, etc.)."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`clearGeometryCache <abaqus.Property.PropertyPart.PropertyPart.clearGeometryCache>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method clears the geometry cache."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`deleteAllFeatures <abaqus.Property.PropertyPart.PropertyPart.deleteAllFeatures>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method deletes all the features in the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`deleteFeatures <abaqus.Property.PropertyPart.PropertyPart.deleteFeatures>`\\ \\(featureNames\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method deletes the given features."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getAngle <abaqus.Property.PropertyPart.PropertyPart.getAngle>`\\ \\(plane1\\, plane2\\, line1\\, line2\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the angle between the specified entities."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getArea <abaqus.Property.PropertyPart.PropertyPart.getArea>`\\ \\(faces\\[\\, relativeAccuracy\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the total surface area of a given face or group of faces."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getAssociatedCADPaths <abaqus.Property.PropertyPart.PropertyPart.getAssociatedCADPaths>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the paths to the associated CAD part and root file."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getCADParameters <abaqus.Property.PropertyPart.PropertyPart.getCADParameters>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the names and values of the CAD parameters associated with the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getCentroid <abaqus.Property.PropertyPart.PropertyPart.getCentroid>`\\ \\(faces\\, cells\\[\\, relativeAccuracy\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "Location of the centroid of a given face/cell or group of faces/cells"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getCoordinates <abaqus.Property.PropertyPart.PropertyPart.getCoordinates>`\\ \\(entity\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the coordinates of specified point."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getCurvature <abaqus.Property.PropertyPart.PropertyPart.getCurvature>`\\ \\(edges\\[\\, samplePoints\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the maximum curvature of a given edge or group of edges."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getDistance <abaqus.Property.PropertyPart.PropertyPart.getDistance>`\\ \\(entity1\\, entity2\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "Depending on the arguments provided, this method returns one of the following:"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getLength <abaqus.Property.PropertyPart.PropertyPart.getLength>`\\ \\(edges\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the length of a given edge or group of edges."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getPerimeter <abaqus.Property.PropertyPart.PropertyPart.getPerimeter>`\\ \\(faces\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the total perimeter of a given face or group of faces."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getVolume <abaqus.Property.PropertyPart.PropertyPart.getVolume>`\\ \\(cells\\[\\, relativeAccuracy\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the volume area of a given cell or group of cells."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getMassProperties <abaqus.Property.PropertyPart.PropertyPart.getMassProperties>`\\ \\(\\[regions\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns the mass properties of a part or region."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getFeatureFaces <abaqus.Property.PropertyPart.PropertyPart.getFeatureFaces>`\\ \\(name\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns a sequence of Face objects that are created by the given feature."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getFeatureEdges <abaqus.Property.PropertyPart.PropertyPart.getFeatureEdges>`\\ \\(name\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns a sequence of Edge objects that are created by the given feature."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getFeatureCells <abaqus.Property.PropertyPart.PropertyPart.getFeatureCells>`\\ \\(name\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns a sequence of Cell objects that are created by the given feature."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`getFeatureVertices <abaqus.Property.PropertyPart.PropertyPart.getFeatureVertices>`\\ \\(name\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns a sequence of ConstrainedSketchVertex objects that are created by the given feature."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`isAlignedWithSketch <abaqus.Property.PropertyPart.PropertyPart.isAlignedWithSketch>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method checks if the normal of an analytical rigid surface part is aligned with that of its sketch."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`printAssignedSections <abaqus.Property.PropertyPart.PropertyPart.printAssignedSections>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method prints information on each section that has been assigned to a region of the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`projectEdgesOntoSketch <abaqus.Property.PropertyPart.PropertyPart.projectEdgesOntoSketch>`\\ \\(sketch\\, edges\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method projects the selected edges of a part onto the specified ConstrainedSketch object."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`projectReferencesOntoSketch <abaqus.Property.PropertyPart.PropertyPart.projectReferencesOntoSketch>`\\ \\(sketch\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method projects the vertices of specified edges, and datum points from the part onto the specified ConstrainedSketch object."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`queryAttributes <abaqus.Property.PropertyPart.PropertyPart.queryAttributes>`\\ \\(\\[printResults\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method prints the following information about a part:"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`queryCachedStates <abaqus.Property.PropertyPart.PropertyPart.queryCachedStates>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method displays the position of geometric states relative to the sequence of features in the part cache."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`queryGeometry <abaqus.Property.PropertyPart.PropertyPart.queryGeometry>`\\ \\(\\[relativeAccuracy\\, printResults\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`queryRegionsMissingSections <abaqus.Property.PropertyPart.PropertyPart.queryRegionsMissingSections>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method returns all regions in the part that do not have a section assignment but require one for analysis."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`queryDisjointPlyRegions <abaqus.Property.PropertyPart.PropertyPart.queryDisjointPlyRegions>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method provides a list of all composite plys in the current part which have disjoint regions."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`regenerate <abaqus.Property.PropertyPart.PropertyPart.regenerate>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method regenerates a part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`regenerationWarnings <abaqus.Property.PropertyPart.PropertyPart.regenerationWarnings>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method prints any regeneration warnings associated with the features."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`removeInvalidGeometry <abaqus.Property.PropertyPart.PropertyPart.removeInvalidGeometry>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "Removes all invalid entities from the part, leaving a valid part."
msgstr ""

#: ../../None:65:<autosummary>:1
#: ../../None:68:<autosummary>:1
msgid ":py:obj:`restore <abaqus.Property.PropertyPart.PropertyPart.restore>`\\ \\(\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
#: ../../None:68:<autosummary>:1
msgid "This method restores the parameters of all features in the assembly to the value they had before a failed regeneration."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`resumeAllFeatures <abaqus.Property.PropertyPart.PropertyPart.resumeAllFeatures>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method resumes all the suppressed features in the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`resumeFeatures <abaqus.Property.PropertyPart.PropertyPart.resumeFeatures>`\\ \\(featureNames\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method resumes the specified suppressed features in the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`resumeLastSetFeatures <abaqus.Property.PropertyPart.PropertyPart.resumeLastSetFeatures>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method resumes the last set of features to be suppressed in the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`saveGeometryCache <abaqus.Property.PropertyPart.PropertyPart.saveGeometryCache>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method caches the current geometry."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`setAssociatedCADPaths <abaqus.Property.PropertyPart.PropertyPart.setAssociatedCADPaths>`\\ \\(\\[partFile\\, rootFile\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method sets the paths to the associated CAD part and root file."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`suppressFeatures <abaqus.Property.PropertyPart.PropertyPart.suppressFeatures>`\\ \\(featureNames\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method suppresses the given features."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`writeAcisFile <abaqus.Property.PropertyPart.PropertyPart.writeAcisFile>`\\ \\(fileName\\[\\, version\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method exports the geometry of the part to a named file in ACIS format."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`writeCADParameters <abaqus.Property.PropertyPart.PropertyPart.writeCADParameters>`\\ \\(paramFile\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method writes the parameters that were imported from the CAD system to a parameter file."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`writeIgesFile <abaqus.Property.PropertyPart.PropertyPart.writeIgesFile>`\\ \\(fileName\\, flavor\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method exports the geometry of the part to a named file in IGES format."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`writeStepFile <abaqus.Property.PropertyPart.PropertyPart.writeStepFile>`\\ \\(fileName\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method exports the geometry of the part to a named file in STEP format."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`writeVdaFile <abaqus.Property.PropertyPart.PropertyPart.writeVdaFile>`\\ \\(fileName\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method exports the geometry of the part to a named file in VDA-FS format."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`copyMeshPattern <abaqus.Property.PropertyPart.PropertyPart.copyMeshPattern>`\\ \\(elements\\, faces\\, elemFaces\\, ...\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method copies a mesh pattern from a source region consisting of a set of shell elements or element faces onto a target face, mapping nodes and elements in a one-one correspondence between source and target."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`smoothNodes <abaqus.Property.PropertyPart.PropertyPart.smoothNodes>`\\ \\(nodes\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method smooths the given nodes of a native mesh, moving them locally to a more optimal location that improves the quality of the mesh"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`Lock <abaqus.Property.PropertyPart.PropertyPart.Lock>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method locks the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`Unlock <abaqus.Property.PropertyPart.PropertyPart.Unlock>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method unlocks the part."
msgstr ""

#: ../../None:68:<autosummary>:1
msgid ":py:obj:`LockForUpgrade <abaqus.Property.PropertyPart.PropertyPart.LockForUpgrade>`\\ \\(\\)"
msgstr ""

#: ../../None:68:<autosummary>:1
msgid "This method locks the part for upgrade."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`AutoRepair <abaqus.Property.PropertyPart.PropertyPart.AutoRepair>`\\ \\(\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method carries out a sequence of geometry repair operations if it contains invalid entities."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`AddCells <abaqus.Property.PropertyPart.PropertyPart.AddCells>`\\ \\(faceList\\[\\, flipped\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method tries to convert a shell entity to a solid entity."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`AnalyticRigidSurf2DPlanar <abaqus.Property.PropertyPart.PropertyPart.AnalyticRigidSurf2DPlanar>`\\ \\(sketch\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object for an analytical rigid surface by creating a planar wire from the given ConstrainedSketch object."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`AnalyticRigidSurfExtrude <abaqus.Property.PropertyPart.PropertyPart.AnalyticRigidSurfExtrude>`\\ \\(sketch\\[\\, depth\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object for an analytical rigid surface by extruding the given ConstrainedSketch object by the given depth, creating a surface."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`AnalyticRigidSurfRevolve <abaqus.Property.PropertyPart.PropertyPart.AnalyticRigidSurfRevolve>`\\ \\(sketch\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object for an analytical rigid surface by revolving the given ConstrainedSketch object by 360Â° about the **Y**-axis."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`AssignMidsurfaceRegion <abaqus.Property.PropertyPart.PropertyPart.AssignMidsurfaceRegion>`\\ \\(cellList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method assign a mid-surface property to sequence of Cell objects."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseSolidExtrude <abaqus.Property.PropertyPart.PropertyPart.BaseSolidExtrude>`\\ \\(sketch\\, depth\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by extruding the given ConstrainedSketch object by the given depth, creating a solid."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseSolidRevolve <abaqus.Property.PropertyPart.PropertyPart.BaseSolidRevolve>`\\ \\(sketch\\, angle\\[\\, pitch\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by revolving the given ConstrainedSketch object by the given angle, creating a solid."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseSolidSweep <abaqus.Property.PropertyPart.PropertyPart.BaseSolidSweep>`\\ \\(sketch\\, path\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by sweeping the given profile ConstrainedSketch object along the path defined by the path ConstrainedSketch object, creating a solid."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseShell <abaqus.Property.PropertyPart.PropertyPart.BaseShell>`\\ \\(sketch\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by creating a planar shell from the given ConstrainedSketch object."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseShellExtrude <abaqus.Property.PropertyPart.PropertyPart.BaseShellExtrude>`\\ \\(sketch\\, depth\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by extruding the given ConstrainedSketch object by the given depth, creating a shell."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseShellRevolve <abaqus.Property.PropertyPart.PropertyPart.BaseShellRevolve>`\\ \\(sketch\\, angle\\[\\, pitch\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by revolving the given ConstrainedSketch object by the given angle, creating a shell."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseShellSweep <abaqus.Property.PropertyPart.PropertyPart.BaseShellSweep>`\\ \\(sketch\\, path\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by sweeping the given section ConstrainedSketch object along the path defined by the path ConstrainedSketch object, creating a shell."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BaseWire <abaqus.Property.PropertyPart.PropertyPart.BaseWire>`\\ \\(sketch\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a first Feature object by creating a planar wire from the given ConstrainedSketch object."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`BlendFaces <abaqus.Property.PropertyPart.PropertyPart.BlendFaces>`\\ \\(side1\\, side2\\[\\, method\\, path\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a Feature object by creating new faces that blends two sets of faces."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Chamfer <abaqus.Property.PropertyPart.PropertyPart.Chamfer>`\\ \\(length\\, edgeList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by chamfering the given list of edges with a given length."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Mirror <abaqus.Property.PropertyPart.PropertyPart.Mirror>`\\ \\(mirrorPlane\\, keepOriginal\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method mirrors existing part geometry across a plane to create new geometry."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ConvertToAnalytical <abaqus.Property.PropertyPart.PropertyPart.ConvertToAnalytical>`\\ \\(\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method attempts to change entities into a simpler form that will speed up processing and make entities available during feature operations."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ConvertToPrecise <abaqus.Property.PropertyPart.PropertyPart.ConvertToPrecise>`\\ \\(\\[method\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method attempts to change imprecise entities so that the geometry becomes precise."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`CoverEdges <abaqus.Property.PropertyPart.PropertyPart.CoverEdges>`\\ \\(edgeList\\[\\, tryAnalytical\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method generates a face using the given edges as the face's boundaries."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Cut <abaqus.Property.PropertyPart.PropertyPart.Cut>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by cutting a hole using the given ConstrainedSketch object."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`CutExtrude <abaqus.Property.PropertyPart.PropertyPart.CutExtrude>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by extruding the given ConstrainedSketch object by the given depth and cutting away material in the solid and shell regions of the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`CutLoft <abaqus.Property.PropertyPart.PropertyPart.CutLoft>`\\ \\(loftsections\\[\\, startCondition\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by lofting between the given sections and cutting away material from the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`CutRevolve <abaqus.Property.PropertyPart.PropertyPart.CutRevolve>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by revolving the given ConstrainedSketch object by the given angle and cutting away material from the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`CutSweep <abaqus.Property.PropertyPart.PropertyPart.CutSweep>`\\ \\(path\\, profile\\[\\, pathPlane\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by sweeping the given ConstrainedSketch object along a path which may be a ConstrainedSketch or a sequence of Edge objects and cutting away material from the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ExtendFaces <abaqus.Property.PropertyPart.PropertyPart.ExtendFaces>`\\ \\(\\[faces\\, extendAlong\\, distance\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method extends faces along its free edges by offsetting the external edges along the surfaces."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`FaceFromElementFaces <abaqus.Property.PropertyPart.PropertyPart.FaceFromElementFaces>`\\ \\(elementFaces\\[\\, stitch\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates a geometry face from a collection of orphan element faces."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`HoleBlindFromEdges <abaqus.Property.PropertyPart.PropertyPart.HoleBlindFromEdges>`\\ \\(plane\\, planeSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a circular blind hole of the given diameter and depth and cutting away material in the solid and shell regions of the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`HoleFromEdges <abaqus.Property.PropertyPart.PropertyPart.HoleFromEdges>`\\ \\(diameter\\, edge1\\, distance1\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a circular hole of the given diameter in a 2D planar part and cutting away material in the shell and wire regions of the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`HoleThruAllFromEdges <abaqus.Property.PropertyPart.PropertyPart.HoleThruAllFromEdges>`\\ \\(plane\\, planeSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a circular through hole of the given diameter and cutting away material in the solid and shell regions of the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`MergeEdges <abaqus.Property.PropertyPart.PropertyPart.MergeEdges>`\\ \\(\\[edgeList\\, extendSelection\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method merges edges either by extending the user selection or using only the selected edges."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`OffsetFaces <abaqus.Property.PropertyPart.PropertyPart.OffsetFaces>`\\ \\(faceList\\[\\, distance\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates new faces by offsetting existing faces."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RemoveCells <abaqus.Property.PropertyPart.PropertyPart.RemoveCells>`\\ \\(cellList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method converts a solid entity to a shell entity."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RemoveFaces <abaqus.Property.PropertyPart.PropertyPart.RemoveFaces>`\\ \\(faceList\\[\\, deleteCells\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method removes faces from a solid entity or from a shell entity."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RemoveFacesAndStitch <abaqus.Property.PropertyPart.PropertyPart.RemoveFacesAndStitch>`\\ \\(faceList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method removes faces from a solid entity and attempts to close the resulting gap by extending the neighboring faces of the solid."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RemoveRedundantEntities <abaqus.Property.PropertyPart.PropertyPart.RemoveRedundantEntities>`\\ \\(\\[vertexList\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method removes redundant edges and vertices from a solid or a shell entity."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RepairFaceNormals <abaqus.Property.PropertyPart.PropertyPart.RepairFaceNormals>`\\ \\(\\[faceList\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method works on the entire part or a sequence of shell faces."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RepairInvalidEdges <abaqus.Property.PropertyPart.PropertyPart.RepairInvalidEdges>`\\ \\(edgeList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method repairs invalid edges."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RepairSliver <abaqus.Property.PropertyPart.PropertyPart.RepairSliver>`\\ \\(face\\, point1\\, point2\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method repairs the selected sliver from the selected face."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RepairSmallEdges <abaqus.Property.PropertyPart.PropertyPart.RepairSmallEdges>`\\ \\(edgeList\\[\\, toleranceChecks\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method repairs small edges."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`RepairSmallFaces <abaqus.Property.PropertyPart.PropertyPart.RepairSmallFaces>`\\ \\(faceList\\[\\, toleranceChecks\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method repairs small faces."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ReplaceFaces <abaqus.Property.PropertyPart.PropertyPart.ReplaceFaces>`\\ \\(faceList\\[\\, stitch\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method replaces the selected faces with a single face."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Round <abaqus.Property.PropertyPart.PropertyPart.Round>`\\ \\(radius\\, edgeList\\, vertexList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by rounding (filleting) the given list of entities with the given radius."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Shell <abaqus.Property.PropertyPart.PropertyPart.Shell>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a planar shell from the given ConstrainedSketch object."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ShellExtrude <abaqus.Property.PropertyPart.PropertyPart.ShellExtrude>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by extruding the given ConstrainedSketch object by the given depth, creating a shell protrusion."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ShellLoft <abaqus.Property.PropertyPart.PropertyPart.ShellLoft>`\\ \\(loftsections\\[\\, startCondition\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by lofting between the given sections and adding shell faces to the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ShellRevolve <abaqus.Property.PropertyPart.PropertyPart.ShellRevolve>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by revolving the given ConstrainedSketch object by the given angle, creating a shell protrusion."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`ShellSweep <abaqus.Property.PropertyPart.PropertyPart.ShellSweep>`\\ \\(path\\, profile\\[\\, pathPlane\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by sweeping the given ConstrainedSketch object or a sequence of Edge objects along a path which may be a ConstrainedSketch or a sequence of Edge objects, creating a shell swept protrusion."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`SolidExtrude <abaqus.Property.PropertyPart.PropertyPart.SolidExtrude>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by extruding the given ConstrainedSketch object by the given depth, creating a solid protrusion."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`SolidLoft <abaqus.Property.PropertyPart.PropertyPart.SolidLoft>`\\ \\(loftsections\\[\\, startCondition\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by lofting between the given sections and adding material to the part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`SolidRevolve <abaqus.Property.PropertyPart.PropertyPart.SolidRevolve>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by revolving the given ConstrainedSketch object by the given angle, creating a solid protrusion."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`SolidSweep <abaqus.Property.PropertyPart.PropertyPart.SolidSweep>`\\ \\(path\\, profile\\[\\, pathPlane\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by sweeping the given ConstrainedSketch object or a Face object along a path which may be a ConstrainedSketch or a sequence of Edge objects, creating a solid swept protrusion."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Stitch <abaqus.Property.PropertyPart.PropertyPart.Stitch>`\\ \\(\\[edgeList\\, stitchTolerance\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method attempts to create a valid part by binding together free and imprecise edges of all the faces of a part."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`Wire <abaqus.Property.PropertyPart.PropertyPart.Wire>`\\ \\(sketchPlane\\, sketchPlaneSide\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a planar wire from the given ConstrainedSketch object."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`WireSpline <abaqus.Property.PropertyPart.PropertyPart.WireSpline>`\\ \\(points\\[\\, mergeType\\, ...\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a spline wire that passes through a sequence of given points."
msgstr ""

#: ../../None:59:<autosummary>:1
#: ../../None:65:<autosummary>:1
msgid ":py:obj:`WirePolyLine <abaqus.Property.PropertyPart.PropertyPart.WirePolyLine>`\\ \\(points\\[\\, mergeType\\, meshable\\]\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
#: ../../None:65:<autosummary>:1
msgid "This method creates an additional Feature object by creating a polyline wire that passes through a sequence of given points."
msgstr ""

#: ../../None:59:<autosummary>:1
msgid ":py:obj:`WireFromEdge <abaqus.Property.PropertyPart.PropertyPart.WireFromEdge>`\\ \\(edgeList\\)"
msgstr ""

#: ../../None:59:<autosummary>:1
msgid "This method creates an additional Feature object by creating a Wire by selecting one or more Edge objects of a Solid or Shell part."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`AttachmentPoints <abaqus.Property.PropertyPart.PropertyPart.AttachmentPoints>`\\ \\(name\\, points\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates an attachment points Feature."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`AttachmentPointsAlongDirection <abaqus.Property.PropertyPart.PropertyPart.AttachmentPointsAlongDirection>`\\ \\(name\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object by creating attachment points along a direction or between two points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`AttachmentPointsOffsetFromEdges <abaqus.Property.PropertyPart.PropertyPart.AttachmentPointsOffsetFromEdges>`\\ \\(name\\, edges\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object by creating attachment points along or offset from one or more connected edges."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByCylFace <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByCylFace>`\\ \\(face\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object along the axis of a cylinder or cone."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByNormalToPlane <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByNormalToPlane>`\\ \\(plane\\, point\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object normal to the specified plane and passing through the specified point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByParToEdge <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByParToEdge>`\\ \\(edge\\, point\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object parallel to the specified edge and passing through the specified point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByPrincipalAxis <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByPrincipalAxis>`\\ \\(principalAxis\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object along one of the three principal axes."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByRotation <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByRotation>`\\ \\(\\*args\\, \\*\\*kwargs\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByThreePoint <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByThreePoint>`\\ \\(point1\\, point2\\, point3\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object normal to the circle described by three points and through its center."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByThruEdge <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByThruEdge>`\\ \\(edge\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object along the specified edge."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByTwoPlane <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByTwoPlane>`\\ \\(plane1\\, plane2\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object at the intersection of two planes."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumAxisByTwoPoint <abaqus.Property.PropertyPart.PropertyPart.DatumAxisByTwoPoint>`\\ \\(point1\\, point2\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumAxis object along the line joining two points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumCsysByDefault <abaqus.Property.PropertyPart.PropertyPart.DatumCsysByDefault>`\\ \\(coordSysType\\[\\, name\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumCsys object from the specified default coordinate system at the origin."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumCsysByOffset <abaqus.Property.PropertyPart.PropertyPart.DatumCsysByOffset>`\\ \\(coordSysType\\, ...\\[\\, name\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumCsys object by offsetting the origin of an existing datum coordinate system to a specified point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumCsysByThreePoints <abaqus.Property.PropertyPart.PropertyPart.DatumCsysByThreePoints>`\\ \\(coordSysType\\, origin\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumCsys object from three points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumCsysByTwoLines <abaqus.Property.PropertyPart.PropertyPart.DatumCsysByTwoLines>`\\ \\(coordSysType\\, line1\\, line2\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumCsys object from two orthogonal lines."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByPrincipalPlane <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByPrincipalPlane>`\\ \\(principalPlane\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPlane object through the origin along one of the three principal planes."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByOffset <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByOffset>`\\ \\(\\*args\\, \\*\\*kwargs\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByRotation <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByRotation>`\\ \\(plane\\, axis\\, angle\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPlane object by rotating a plane about the specified axis through the specified angle."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByThreePoints <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByThreePoints>`\\ \\(point1\\, point2\\, point3\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPlane object defined by passing through three points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByLinePoint <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByLinePoint>`\\ \\(line\\, point\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPlane object that pass through the specified line and through the specified point that does not lie on the line."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByPointNormal <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByPointNormal>`\\ \\(point\\, normal\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPlane object normal to the specified line and running through the specified point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPlaneByTwoPoint <abaqus.Property.PropertyPart.PropertyPart.DatumPlaneByTwoPoint>`\\ \\(point1\\, point2\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPlane object midway between two points and normal to the line connecting the points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByCoordinate <abaqus.Property.PropertyPart.PropertyPart.DatumPointByCoordinate>`\\ \\(coords\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object at the point defined by the specified coordinates."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByOffset <abaqus.Property.PropertyPart.PropertyPart.DatumPointByOffset>`\\ \\(point\\, vector\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object offset from an existing point by a vector."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByMidPoint <abaqus.Property.PropertyPart.PropertyPart.DatumPointByMidPoint>`\\ \\(point1\\, point2\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object midway between two points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByOnFace <abaqus.Property.PropertyPart.PropertyPart.DatumPointByOnFace>`\\ \\(face\\, edge1\\, offset1\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object on the specified face, offset from two edges."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByEdgeParam <abaqus.Property.PropertyPart.PropertyPart.DatumPointByEdgeParam>`\\ \\(edge\\, parameter\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object along an edge at a selected distance from one end of the edge."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByProjOnEdge <abaqus.Property.PropertyPart.PropertyPart.DatumPointByProjOnEdge>`\\ \\(point\\, edge\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object along an edge by projecting an existing point along the normal to the edge."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`DatumPointByProjOnFace <abaqus.Property.PropertyPart.PropertyPart.DatumPointByProjOnFace>`\\ \\(point\\, face\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a DatumPoint object on a specified face by projecting an existing point onto the face."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`MakeSketchTransform <abaqus.Property.PropertyPart.PropertyPart.MakeSketchTransform>`\\ \\(sketchPlane\\[\\, origin\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Transform object."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByDatumPlane <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByDatumPlane>`\\ \\(cells\\, datumPlane\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells using the given datum plane."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByExtendFace <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByExtendFace>`\\ \\(cells\\, extendFace\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells by extending the underlying geometry of a given face to partition the target cells."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByExtrudeEdge <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByExtrudeEdge>`\\ \\(cells\\, edges\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells by extruding selected edges in the given direction."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByPatchNCorners <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByPatchNCorners>`\\ \\(cell\\, cornerPoints\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions a cell using an N-sided cutting patch defined by the given corner points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByPatchNEdges <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByPatchNEdges>`\\ \\(cell\\, edges\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions a cell using an N-sided cutting patch defined by the given edges."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByPlaneNormalToEdge <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByPlaneNormalToEdge>`\\ \\(cells\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells using a plane normal to an edge at the given edge point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByPlanePointNormal <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByPlanePointNormal>`\\ \\(cells\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells using a plane defined by a point and a normal direction."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellByPlaneThreePoints <abaqus.Property.PropertyPart.PropertyPart.PartitionCellByPlaneThreePoints>`\\ \\(cells\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells using a plane defined by three points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionCellBySweepEdge <abaqus.Property.PropertyPart.PropertyPart.PartitionCellBySweepEdge>`\\ \\(cells\\, edges\\, sweepPath\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more cells by sweeping selected edges along the given sweep path."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionEdgeByDatumPlane <abaqus.Property.PropertyPart.PropertyPart.PartitionEdgeByDatumPlane>`\\ \\(edges\\, datumPlane\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions an edge where it intersects with a datum plane."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionEdgeByParam <abaqus.Property.PropertyPart.PropertyPart.PartitionEdgeByParam>`\\ \\(edges\\, parameter\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more edges at the given normalized edge parameter."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionEdgeByPoint <abaqus.Property.PropertyPart.PropertyPart.PartitionEdgeByPoint>`\\ \\(edge\\, point\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions an edge at the given point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByAuto <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByAuto>`\\ \\(face\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method automatically partitions a target face into simple regions that can be meshed using a structured meshing technique."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByCurvedPathEdgeParams <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByCurvedPathEdgeParams>`\\ \\(face\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions a face normal to two edges, using a curved path between the two given edge points defined by the normalized edge parameters."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByCurvedPathEdgePoints <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByCurvedPathEdgePoints>`\\ \\(face\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions a face normal to two edges, using a curved path between the two given edge points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByDatumPlane <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByDatumPlane>`\\ \\(faces\\, datumPlane\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces using the given datum plane."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByExtendFace <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByExtendFace>`\\ \\(faces\\, extendFace\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces by extending the underlying geometry of another given face to partition the target faces."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByIntersectFace <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByIntersectFace>`\\ \\(faces\\, cuttingFaces\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces using the given cutting faces to partition the target faces."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByProjectingEdges <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByProjectingEdges>`\\ \\(faces\\, edges\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces by projecting the given edges on the target faces."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceByShortestPath <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceByShortestPath>`\\ \\(faces\\, point1\\, ...\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces using a minimum distance path between the two given points."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceBySketch <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceBySketch>`\\ \\(faces\\, sketch\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more planar faces by sketching on them."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceBySketchDistance <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceBySketchDistance>`\\ \\(faces\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces by sketching on a sketch plane and then projecting the sketch toward the target faces through the given distance."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceBySketchRefPoint <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceBySketchRefPoint>`\\ \\(faces\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces by sketching on a sketch plane and then projecting the sketch toward the target faces through a distance governed by the reference point."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`PartitionFaceBySketchThruAll <abaqus.Property.PropertyPart.PropertyPart.PartitionFaceBySketchThruAll>`\\ \\(faces\\, ...\\[\\, ...\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method partitions one or more faces by sketching on a sketch plane and then projecting toward the target faces through an infinite distance."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`ReferencePoint <abaqus.Property.PropertyPart.PropertyPart.ReferencePoint>`\\ \\(point\\[\\, instanceName\\]\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method creates a Feature object and a ReferencePoint object at the specified location."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`RemoveWireEdges <abaqus.Property.PropertyPart.PropertyPart.RemoveWireEdges>`\\ \\(wireEdgeList\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method removes wire edges."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`isSuppressed <abaqus.Property.PropertyPart.PropertyPart.isSuppressed>`\\ \\(\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method queries the suppressed state of the feature."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`resume <abaqus.Property.PropertyPart.PropertyPart.resume>`\\ \\(\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method resumes suppressed features."
msgstr ""

#: ../../None:65:<autosummary>:1
msgid ":py:obj:`suppress <abaqus.Property.PropertyPart.PropertyPart.suppress>`\\ \\(\\)"
msgstr ""

#: ../../None:65:<autosummary>:1
msgid "This method suppresses features."
msgstr ""
